# Routes must also be added to content/settings/routes.yaml
routes:
  /signup/: signup
  /signup-success/: signup-success
  /events/: events
  /perpetual-brew-2/: perpetual-brew

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
